Adding X_normalization check
Lattice-Data/lattice-tools pull request #92
Opened 2023-08-10 22:06 UTC by Jchaffer787

If 'X_normalization' of mfinal_adata is false, then the raw matrix is set to be the X of cxg_adata. This is in order to allow flattening Processed matrices that only have raw matrix counts.

2023-08-11 00:54 UTC, jahilton requested changes
I'm not sure that this is sufficient to achieve the desired result.
If I'm reading it right, then you set cxg_adata to be AnnData with the raw counts in X, but then a little lower in the code `cxg_adata.raw = cxg_adata_raw` is just going to set the .raw to be that same layer
So I think you're going to end up with duplicate raw count layers.

2023-08-11 17:05 UTC, jychien commented
I've left comment on Jira ticket: https://lattice.atlassian.net/browse/TOOLS-120?focusedCommentId=16410

2023-08-11 20:59 UTC, Jchaffer787 commented
I've committed a change to the placement of 'X_normalization', and also included a check in quality_check function to prevent an error.

2023-08-11 22:00 UTC, jychien commented
Got the following error when running on LATDF708XLX:

> 
> Traceback (most recent call last):
>   File "/Users/jychien/Lattice-Data/lattice-tools/scripts/flattener.py", line 1429, in <module>
>     main(args.file)
>   File "/Users/jychien/Lattice-Data/lattice-tools/scripts/flattener.py", line 1421, in main
>     quality_check(cxg_adata)
>   File "/Users/jychien/Lattice-Data/lattice-tools/scripts/flattener.py", line 596, in quality_check
>     elif mfinal_adata['X_normalized'] == True:
>   File "/Users/jychien/miniconda3/envs/flattener_0.8/lib/python3.9/site-packages/anndata/_core/anndata.py", line 1113, in __getitem__
>     oidx, vidx = self._normalize_indices(index)
>   File "/Users/jychien/miniconda3/envs/flattener_0.8/lib/python3.9/site-packages/anndata/_core/anndata.py", line 1094, in _normalize_indices
>     return _normalize_indices(index, self.obs_names, self.var_names)
>   File "/Users/jychien/miniconda3/envs/flattener_0.8/lib/python3.9/site-packages/anndata/_core/index.py", line 35, in _normalize_indices
>     ax0 = _normalize_index(ax0, names0)
>   File "/Users/jychien/miniconda3/envs/flattener_0.8/lib/python3.9/site-packages/anndata/_core/index.py", line 75, in _normalize_index
>     return index.get_loc(indexer)  # int
>   File "/Users/jychien/miniconda3/envs/flattener_0.8/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3631, in get_loc
>     raise KeyError(key) from err
> KeyError: 'X_normalized'

2023-08-11 22:02 UTC, Jchaffer787 commented
Whoops! That should be 'mfinal_obj' not 'mfinal_adata'. Thanks for catching that Jenny!

2023-08-12 00:12 UTC, jychien commented
Thanks, Jim! Looks good, but I haven't had a chance to run some other datasets to make sure things are running smoothly for those. Maybe we can look at it next week and see if this ticket is applicable: https://lattice.atlassian.net/browse/WRN-644

2023-08-18 00:03 UTC, jychien commented
This looks good to me! Thanks, Jim! This is the first time I've seen a "Changes requested" for a PR. Hopefully you are still able to merge it.

2023-08-18 00:05 UTC, merged